# Generated by Django 3.1.2 on 2020-11-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fccProfileUrl',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
