# Generated by Django 3.1.1 on 2020-09-08 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200908_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['-createdAt'], 'verbose_name_plural': 'Order Status'},
        ),
        migrations.AlterModelOptions(
            name='ordertype',
            options={'ordering': ['-createdAt'], 'verbose_name_plural': 'Order Types'},
        ),
        migrations.AlterModelOptions(
            name='pacient',
            options={'verbose_name_plural': 'Pacients'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='warranty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
