# Generated by Django 3.1.1 on 2020-09-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cabinet',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='details',
            field=models.TextField(max_length=300),
        ),
    ]
