# Generated by Django 3.1.1 on 2020-10-04 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200921_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertype',
            name='pricePerUnit',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
