# Generated by Django 3.1.1 on 2020-10-04 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_ordertype_priceperunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='pricePerUnit',
            field=models.IntegerField(default=0, verbose_name=django.core.validators.MinValueValidator(0)),
            preserve_default=False,
        ),
    ]
