# Generated by Django 3.1.1 on 2020-10-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20201004_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertype',
            old_name='pricePerUnit',
            new_name='ppu',
        ),
    ]
