# Generated by Django 3.1.2 on 2020-11-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20201103_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.doctor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.patient'),
        ),
        migrations.AlterField(
            model_name='ordertypeentry',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.ordercolor'),
        ),
        migrations.AlterField(
            model_name='ordertypeentry',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.orderstatus'),
        ),
        migrations.AlterField(
            model_name='ordertypeentry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.ordertype'),
        ),
    ]
